[package]
name = "codesum"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }

[dev-dependencies]
assert_cmd = { version = "2.0.15" }
predicates = { version = "3.1.2" }